# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cache.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63\x61\x63he.proto\x12\x05\x63\x61\x63he\"\x12\n\x03Key\x12\x0b\n\x03key\x18\x01 \x01(\t\"\'\n\tKey_Value\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x1f\n\tPostReply\x12\x12\n\npost_reply\x18\x01 \x01(\x08\"/\n\x08GetReply\x12\x11\n\tget_reply\x18\x01 \x01(\t\x12\x10\n\x08in_cache\x18\x02 \x01(\x08\"#\n\x0b\x44\x65leteReply\x12\x14\n\x0c\x64\x65lete_reply\x18\x01 \x01(\x08\x32\x87\x01\n\x05\x43\x61\x63he\x12,\n\x04post\x12\x10.cache.Key_Value\x1a\x10.cache.PostReply\"\x00\x12$\n\x03get\x12\n.cache.Key\x1a\x0f.cache.GetReply\"\x00\x12*\n\x06\x64\x65lete\x12\n.cache.Key\x1a\x12.cache.DeleteReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cache_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_KEY']._serialized_start=22
  _globals['_KEY']._serialized_end=40
  _globals['_KEY_VALUE']._serialized_start=42
  _globals['_KEY_VALUE']._serialized_end=81
  _globals['_POSTREPLY']._serialized_start=83
  _globals['_POSTREPLY']._serialized_end=114
  _globals['_GETREPLY']._serialized_start=116
  _globals['_GETREPLY']._serialized_end=163
  _globals['_DELETEREPLY']._serialized_start=165
  _globals['_DELETEREPLY']._serialized_end=200
  _globals['_CACHE']._serialized_start=203
  _globals['_CACHE']._serialized_end=338
# @@protoc_insertion_point(module_scope)
