version: '3'

services:

  'service_9527':
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9527:9527"
      - "5000:4666"
    environment:
      - FLASK_PORT=9527
      - GRPC_ADDRESS=2


  'service_9528':
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9528:9528"
      - "5001:4666"
    environment:
      - FLASK_PORT=9528
      - GRPC_ADDRESS=3


  'service_9529':
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9529:9529"
      - "5002:4666"
    environment:
      - FLASK_PORT=9529
      - GRPC_ADDRESS=4
